# Generated by Django 4.2.6 on 2023-10-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description_short', models.TextField(max_length=150)),
                ('description_long', models.TextField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('price', models.FloatField()),
                ('price_promo', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('V', 'Variation'), ('N', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
